
services:
  # frontend Mobile
  react-native-dev:
    build: 
      context: ./App
    environment:
      TZ: America/Guayaquil
      DISPLAY: $DISPLAY
      ADB_ENDPOINT: 192.168.67.5:55555
      API_BASE_URL: http://192.168.67.245:8080/api/
      DEFAULT_USERNAME: walecel
      DEFAULT_PASSWORD: p4s$w0rD
      #MOCKED_LOCATION: 2.1260429,79.9876802
    entrypoint: bash ./boot.sh
    hostname: react-native-dev
    networks:
      tesis-vpn:
        ipv4_address: 192.168.67.243
      #backend:
    user: "1000:1000"
    volumes:
      - ./App:/Project
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./App/Data:/home/AndroidStudio
      - ./Common:/Common
    working_dir: /Project
  react-native-production-build:
    build: 
      context: ./App
    environment:
      TZ: America/Guayaquil
      ADB_ENDPOINT: 192.168.147.2:55555
      API_BASE_URL: https://api.71walceli.beauty/ccmangos/api
      DEFAULT_USERNAME: walecel
      DEFAULT_PASSWORD: p4s5w0rD
      KEY_PASSPHRASE: p4s5w0rD
      APP_ID_SUFFIX: staging
      #CLEAN: "true"
    entrypoint: bash ./build.sh
    user: "1000:1000"
    volumes:
      - ./App:/Project
      - ./App/Data:/home/AndroidStudio
      - ./Common:/Common
    working_dir: /Project

  # Frontend Web
  web:
    entrypoint: yarn start
    environment:
      REACT_APP_API_BASE_URL: http://192.168.67.245:8080/api/
    hostname: web
    networks:
      tesis-vpn:
        ipv4_address: 192.168.67.244
      #backend:
    image: node:20
    volumes:
      - ./Web:/App
      - ./Common:/Common
    working_dir: /App
  
  # Backend
  django:
    build:
      context: ./Backend
      args:
        UID: 1000
        GID: 1000
      dockerfile: django.Dockerfile
    depends_on:
      - postgres
    hostname: django
    networks:
      tesis-vpn:
        ipv4_address: 192.168.67.245
      backend:
    user: "1000:1000"
    volumes:
      - ./Backend:/App
      - ./Backend/Data/uploads:/Uploads
    working_dir: /App
  
  postgres:
    build:
      context: ./Backend
      args:
        UID: 1000
        GID: 1000
      dockerfile: postgres.Dockerfile
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    hostname: postgres
    networks:
      backend:
    user: "1000:1000"
    #restart: unless-stopped
    volumes:
      - ./Backend/Data/postgresql:/var/lib/postgresql/data

  # Machine Learning Core
  predictive-model-training:
    build:
      context: ./PredictiveModel
      args:
        UID: 1000
        GID: 1000
    hostname: predictive-model-training
    networks:
      tesis-vpn:
        ipv4_address: 192.168.67.246
      #backend:
    shm_size: 8gb
    user: "1000:1000"
    volumes:
      - ./PredictiveModel/Config:/Config
      - ./PredictiveModel/Notebooks:/Notebooks
      - ./PredictiveModel/Content:/content
networks:
  tesis-vpn:
    ipam: 
      config:
        - subnet: 192.168.67.240/29
          gateway: 192.168.67.241
  backend:
